/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Opening_Page;

import View_Admin_Page.Admin_Page;
import View_Seller_Page.Seller_Login_Page;
import View_User_Page.LoginPage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author asuna
 */
public class Opening_Page_Pt_2 extends javax.swing.JFrame {

    /**
     * Creates new form Opening_Page_Pt_2
     */
    public Opening_Page_Pt_2() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Btn = new javax.swing.JLabel();
        Pengguna_Btn = new javax.swing.JLabel();
        Penjual_Btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Admin Btn.png"))); // NOI18N
        Admin_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admin_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admin_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Admin_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Admin_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Admin_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1464, 522, -1, -1));

        Pengguna_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Pengguna Btn.png"))); // NOI18N
        Pengguna_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pengguna_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pengguna_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pengguna_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pengguna_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Pengguna_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Pengguna_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1138, 522, -1, -1));

        Penjual_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Penjual Btn.png"))); // NOI18N
        Penjual_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Penjual_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Penjual_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Penjual_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Penjual_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Penjual_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Penjual_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 522, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Opening Page/Part 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Penjual_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Penjual_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Penjual; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Penjual = new ImageIcon("src/Picture/Effect/Penjual Btn Effect 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Penjual_Btn.setIcon(Btn_Penjual); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        Seller_Login_Page a = new Seller_Login_Page();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Penjual_BtnMouseClicked

    private void Penjual_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Penjual_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Penjual; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Penjual = new ImageIcon("src/Picture/Effect/Penjual Btn Effect 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Penjual_Btn.setIcon(Btn_Penjual); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Penjual_BtnMouseEntered

    private void Penjual_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Penjual_BtnMouseExited
        // TODO add your handling code here:
        ImageIcon Btn_Penjual; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Penjual = new ImageIcon("src/Picture/Effect/Penjual Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Penjual_Btn.setIcon(Btn_Penjual); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
    }//GEN-LAST:event_Penjual_BtnMouseExited

    private void Penjual_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Penjual_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Penjual; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Penjual = new ImageIcon("src/Picture/Effect/Penjual Btn Effect 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Penjual_Btn.setIcon(Btn_Penjual); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Penjual_BtnMousePressed

    private void Penjual_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Penjual_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Penjual; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Penjual = new ImageIcon("src/Picture/Effect/Penjual Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Penjual_Btn.setIcon(Btn_Penjual); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Penjual_BtnMouseReleased

    private void Pengguna_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pengguna_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Pengguna; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Pengguna = new ImageIcon("src/Picture/Effect/Pengguna Btn Effect 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Pengguna_Btn.setIcon(Btn_Pengguna); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        LoginPage  a = new LoginPage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Pengguna_BtnMouseClicked

    private void Pengguna_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pengguna_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Pengguna; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Pengguna = new ImageIcon("src/Picture/Effect/Pengguna Btn Effect 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Pengguna_Btn.setIcon(Btn_Pengguna); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Pengguna_BtnMouseEntered

    private void Pengguna_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pengguna_BtnMouseExited
        // TODO add your handling code here:
        ImageIcon Btn_Pengguna; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Pengguna = new ImageIcon("src/Picture/Effect/Pengguna Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Pengguna_Btn.setIcon(Btn_Pengguna); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Pengguna_BtnMouseExited

    private void Pengguna_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pengguna_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Pengguna; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Pengguna = new ImageIcon("src/Picture/Effect/Pengguna Btn Effect 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Pengguna_Btn.setIcon(Btn_Pengguna); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Pengguna_BtnMousePressed

    private void Pengguna_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pengguna_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Pengguna; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Pengguna = new ImageIcon("src/Picture/Effect/Pengguna Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Pengguna_Btn.setIcon(Btn_Pengguna); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Pengguna_BtnMouseReleased

    private void Admin_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Admin; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Admin = new ImageIcon("src/Picture/Effect/Admin Btn Effect 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Admin_Btn.setIcon(Btn_Admin); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        Admin_Page a = new Admin_Page();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Admin_BtnMouseClicked

    private void Admin_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Admin; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Admin = new ImageIcon("src/Picture/Effect/Admin Btn Effect 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Admin_Btn.setIcon(Btn_Admin); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Admin_BtnMouseEntered

    private void Admin_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_BtnMouseExited
        // TODO add your handling code here:
        ImageIcon Btn_Admin; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Admin = new ImageIcon("src/Picture/Effect/Admin Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Admin_Btn.setIcon(Btn_Admin); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Admin_BtnMouseExited

    private void Admin_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Admin; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Admin = new ImageIcon("src/Picture/Effect/Admin Btn Effect 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Admin_Btn.setIcon(Btn_Admin); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Admin_BtnMousePressed

    private void Admin_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Admin; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        Btn_Admin = new ImageIcon("src/Picture/Effect/Admin Btn.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Admin_Btn.setIcon(Btn_Admin); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Admin_BtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opening_Page_Pt_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opening_Page_Pt_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opening_Page_Pt_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opening_Page_Pt_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opening_Page_Pt_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Btn;
    private javax.swing.JLabel Pengguna_Btn;
    private javax.swing.JLabel Penjual_Btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
